In [20]:
import tensorflow as tf
print(tf.__version__)

2.1.0


In [27]:
import numpy as np

In [23]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift = 1, drop_remainder = True)

dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[: -1], window[-1:]))
dataset = dataset.shuffle(buffer_size = 10)

dataset = dataset.batch(2).prefetch(1)

In [24]:
for x, y in dataset:
    print("x = ", x.numpy())
    print("y = ", y.numpy())

x =  [[4 5 6 7]
 [1 2 3 4]]
y =  [[8]
 [5]]
x =  [[3 4 5 6]
 [5 6 7 8]]
y =  [[7]
 [9]]
x =  [[0 1 2 3]
 [2 3 4 5]]
y =  [[4]
 [6]]


In [33]:
def windowed_dataset(series, window_size, batch_size, shuffle_buffer):
    dataset = tf.data.Dataset.from_tensor_slices(series)
    dataset = dataset.window(window_size + 1, shift = 1, drop_remainder = True)
    dataset = dataset.flat_map(lambda window: wimdow.batch(window_size + 1))
    dataset = dataset.shuffle(shuffle_buffer)
    dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
    dataset = dataset.batch(batch_size).prefetch(1)
    return dataset

In [32]:
split_time = 1000
time_train = time[:split_time]
x_train = series[:split_time]
time_valid = time[:split_time]
x_valid = series[split_time:]

NameError: name 'time' is not defined